<?php
/**
 * @file
 * Code for the Tests feature.
 */

include_once 'tests.features.inc';


function tests_form_quant_time_form_alter(&$form, $form_state) {
  $form['option']['#access'] = FALSE;
  $form['custom_from']['#access'] = FALSE;
  $form['custom_to']['#access'] = FALSE;
  $opts = $form['period']['#options'];
  $form['period']['#title'] = t("See stats from the last");
  $form['period']['#options'] = array(
    '1_day' => '1 day',
    '3_days' => '3 days',
  ) + $opts;
}
